#!/usr/bin/env bash
# =============================================================================
# setup.sh — Initialize Network Observability Stack
#
# 1. Validates prerequisites (docker, docker compose).
# 2. Generates .env with random secrets if not present.
# 3. Prints next steps.
#
# Usage:
#   ./setup.sh            Normal run
#   ./setup.sh --debug    Enable bash trace (set -x)
# =============================================================================

if [[ "${1:-}" == "--debug" ]]; then
    set -x
    echo "DEBUG: Trace mode enabled."
fi

set -euo pipefail
trap 'echo "ERROR: Script failed at line $LINENO (exit $?)." >&2' ERR

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

gen_alphanum() {
    # Generate an alphanumeric string of length $1
    local len="${1:-16}"
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$len" || true
}

gen_hex() {
    # Generate a hex string of length $1 (in bytes, output is 2x chars)
    local bytes="${1:-20}"
    od -An -tx1 -N"$bytes" /dev/urandom | tr -d ' \n' || true
}

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------

echo "[1/3] Checking prerequisites..."

if ! command -v docker &>/dev/null; then
    echo "ERROR: docker not found. Install Docker first." >&2
    exit 1
fi

if ! docker compose version &>/dev/null; then
    echo "ERROR: 'docker compose' plugin not found." >&2
    exit 1
fi

echo "  docker:         $(docker --version | awk '{print $3}' | tr -d ',')"
echo "  docker compose: $(docker compose version --short)"

# ---------------------------------------------------------------------------
# Generate .env
# ---------------------------------------------------------------------------

echo "[2/3] Generating environment file..."

if [[ -f "$ENV_FILE" ]]; then
    echo "  .env already exists — skipping generation."
    echo "  To regenerate: rm .env && ./setup.sh"
else
    DB_PASS="$(gen_alphanum 16)"
    ADMIN_PASS="$(gen_alphanum 12)"

    cat > "$ENV_FILE" <<ENVEOF
# =============================================================================
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================

# --- Image Versions ----------------------------------------------------------
PROMETHEUS_VERSION=latest
GRAFANA_VERSION=latest
LOKI_VERSION=latest
ALERTMANAGER_VERSION=latest
ALLOY_VERSION=latest
POSTGRES_VERSION=16
SNMP_EXPORTER_VERSION=latest
TELEGRAF_VERSION=latest
MCP_GRAFANA_VERSION=latest

# --- Port Mappings -----------------------------------------------------------
PROMETHEUS_PORT=9090
GRAFANA_PORT=3000
LOKI_PORT=3100
ALERTMANAGER_PORT=9093
SNMP_EXPORTER_PORT=9116
ALLOY_SYSLOG_UDP_PORT=1514
ALLOY_SYSLOG_TCP_PORT=1514
MCP_GRAFANA_PORT=8686

# --- PostgreSQL (Grafana backend) --------------------------------------------
GF_DATABASE_NAME=grafana
GF_DATABASE_USER=grafana
GF_DATABASE_PASSWORD=${DB_PASS}

# --- Grafana -----------------------------------------------------------------
GF_ADMIN_USER=admin
GF_ADMIN_PASSWORD=${ADMIN_PASS}
GF_INSTALL_PLUGINS=

# --- Prometheus --------------------------------------------------------------
PROMETHEUS_RETENTION=30d

# --- MCP Servers -------------------------------------------------------------
MCP_GRAFANA_API_KEY=

# --- Nautobot Integration ----------------------------------------------------
# NAUTOBOT_URL=https://nautobot.lab:8443
# NAUTOBOT_TOKEN=
ENVEOF

    chmod 600 "$ENV_FILE"

    echo ""
    echo "  ┌──────────────────────────────────────────────────────┐"
    echo "  │  Generated Credentials (save these now)              │"
    echo "  ├──────────────────────────────────────────────────────┤"
    echo "  │  Grafana admin user:     admin                       │"
    printf "  │  Grafana admin password: %-28s│\n" "$ADMIN_PASS"
    printf "  │  PostgreSQL password:    %-28s│\n" "$DB_PASS"
    echo "  └──────────────────────────────────────────────────────┘"
    echo ""
fi

# ---------------------------------------------------------------------------
# Next steps
# ---------------------------------------------------------------------------

echo "[3/3] Setup complete."
echo ""
echo "Next steps:"
echo "  1. Review .env and adjust ports/versions as needed."
echo "  2. Start core stack:       docker compose up -d"
echo "  3. Start with SNMP:        docker compose --profile snmp up -d"
echo "  4. Start with gNMI:        docker compose --profile telemetry up -d"
echo "  5. Start with MCP:         docker compose --profile mcp up -d"
echo "  6. Start everything:       docker compose --profile snmp --profile telemetry --profile mcp up -d"
echo ""
echo "  Grafana UI:     http://localhost:${GRAFANA_PORT:-3000}"
echo "  Prometheus UI:  http://localhost:${PROMETHEUS_PORT:-9090}"
echo "  Loki API:       http://localhost:${LOKI_PORT:-3100}"
echo "  Alloy UI:       http://localhost:12345"
echo ""
